### ISSUE TITLE
Cannot put graphqls files in a subfolder

### ISSUE THREAD

**Issue by BenoitAverty** [graphql-java/graphql-spring-boot#10]
Hello,

I've just tried to split my schema.hraphqls file into two files, and I put these two files in a subfolder of my resource folders. Now when I start the application, I get the following exception : 
```
Caused by: java.lang.IllegalStateException: No .graphqls files found on classpath.  Please add a graphql schema to the classpath or add a SchemaParser bean to your application context.
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:46) ~[graphql-spring-boot-autoconfigure-3.1.1.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$48ff3ccb.CGLIB$schemaParser$0(<generated>) ~[graphql-spring-boot-autoconfigure-3.1.1.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$48ff3ccb$$FastClassBySpringCGLIB$$b79ceb0b.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-3.1.1.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$48ff3ccb.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-3.1.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	... 22 common frames omitted
```

Previouslyy, the graphqls file was in `src/main/resources`, now it's in `src/main/resources/graphql`.

Is there a way to put these files in a subfolder without creating my own SchemaParser bean ?

**Comment by apottere** [comment]
Yes, there should be.  I'll look into it.

**Comment by BenoitAverty** [comment]
Thanks for the quick fix !
