### ISSUE TITLE
WebSocketServletAutoConfiguration causing issue in load context test

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-spring-boot#113]
As discussed on Gitter I created a test case for this at https://github.com/marceloverdijk/graphql-spring-boot-test-load-context

See test loading context here: https://github.com/marceloverdijk/graphql-spring-boot-test-load-context/blob/master/src/test/java/com/example/graphqlspringboottestloadcontext/MyApplicationTests.java#L19

```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverEndpointExporter' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:139)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 24 more
Caused by: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
	... 39 more
```

Issue seems to be related to the `GraphQLWebAutoConfiguration` class and websocket support:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverEndpointExporter' defined in class path resource 
[com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
```

**Comment by Hyunhoo-Kwon** [comment]
is it released?

**Comment by j3ernhard** [comment]
Is there any workaround available for this issue?

**Comment by oliemansm** [comment]
@j3ernhard The workaround is to configure the unit test with `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)`.

There's a weird problem blocking this release. The build is failing saying it can't find dependency graphql-java-tools:5.2.4, while it's clearly there: https://search.maven.org/artifact/com.graphql-java/graphql-java-tools/5.2.4/jar. Having the same issue locally actually. Not sure what's causing this or how to fix it. Anybody any ideas?

**Comment by oliemansm** [comment]
@alexcibotari This happens when you apply the workaround mentioned above?

**Comment by alexcibotari** [comment]
@oliemansm , yes. 

In my code I have something like 
```
RequestContextHolder.getRequestAttributes()
SecurityContextHolder.getContext().getAuthentication()
```

**Comment by oliemansm** [comment]
The context itself loads though and the test starts up in the first place? Because it sounds like a different issue. If so, could you raise a separate issue for this and preferably include an example test to reproduce your issue?

**Comment by gsdatta** [comment]
I'm still getting this issue in 5.9 and 5.10

**Comment by oliemansm** [comment]
Have you applied the webenvironment setting as described above?

**Comment by gsdatta** [comment]
The webenvironment setting does work - doesn't seem like a scalable solution for all tests to have to set that (or create an alias annotation just for this purpose)

**Comment by oliemansm** [comment]
When I run [this test](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/master/example-request-scoped-dataloader/src/test/java/graphql/servlet/examples/dataloader/requestscope/ApplicationTest.java) without the web environment param I get the exception from the original issue description. When I add the param it runs without problems.

You're saying that doesn't work in your case. Sounds like you have a different problem than the original issue. So could you raise a new issue then with a clear description and steps to reproduce?

**Comment by gsdatta** [comment]
Sorry, to clarify - when I set the web environment param, the problem goes away. When I remove it, I see the same issue.

I was just wondering whether there's a solution outside of setting the param (e.g. does a newer version have a fix, etc).

**Comment by oliemansm** [comment]
There's no other fix available at the moment. The only thing left to try that comes to mind is to only load the websocket config if a `GraphQLSubscriptionResolver` bean is available.

**Comment by MonsieurMan** [comment]
@oliemansm Do you know what exactly is happening under the hood ? Isn't there a fix we could apply to [the corresponding file](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/master/graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWebsocketAutoConfiguration.java) ?   

I'd like to do it if you provide some guidance. 😃
