### ISSUE TITLE
GraphQL starter duplicates classpath when jar is soft symlinked

### ISSUE THREAD

**Issue by snowe2010** [graphql-java/graphql-spring-boot#47]
`GraphQLJavaToolsAutoConfiguration#schemaParser` finds resources using a wildcard match. This matches *soft* symlinks as well causing issues like:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchemaProvider' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchemaProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLSchema' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is graphql.AssertException: field NON-DUPLICATED-FIELD-HERE redefined
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
```

This seems to only happen if we use the `extend type QueryType` syntax though.

The fix at first glance seemed simple, just check if the file is a symlink, but when attempting to make a PR for this problem I immediately came across a problem because jars are not 'on the filesystem' as a spring `Resource`.

**Comment by oliemansm** [comment]
If it’s on the classpath (through a symlink or directly) you’d want to be able to load graphql schemas from it as well I’d say. Can you provide an example of your setup how to reproduce it? Especially interested in which jars contain the graphqls resources and which the accompanying classes. 

Apparently in your case the file that’s symlinked contains graphqls resources you want to ignore?

There’s a change in the upcoming release where you can configure the schema pattern for finding schemas to load from the class path. Would that be a solution for your situation?

**Comment by oliemansm** [comment]
@snowe2010 Is this still an issue, or not anymore with the latest release and can we close it? See also my previous comment.

**Comment by snowe2010** [comment]
Sorry, I forgot to respond to this message. Github doesn't make it easy to remember to do things later. 

> If it’s on the classpath (through a symlink or directly) you’d want to be able to load graphql schemas from it as well I’d say. Can you provide an example of your setup how to reproduce it? Especially interested in which jars contain the graphqls resources and which the accompanying classes.

I don't really care if it's loading symlinks, but that appeared to be the issue that graphql was encountering when using the `extend type` syntax. I can't provide a code example, but I could provide the architecture, but I don't think that would be much help. 
The issue we encountered was that we have many many schemas, and if you need to extend one then you try to use the `extend type` notation and get the above error.
