### ISSUE TITLE
Update to GraphQL Java 8.0

### ISSUE THREAD

**Issue by elenigen** [graphql-java/graphql-spring-boot#68]
GraphQL Java 8.0 is out with great new features & bug fixes. Hope to see Spring Boot support soon!

**Comment by champagne** [comment]
Yes, the class of **graphql.execution.instrumentation.NoOpInstrumentation** is removed since GraphQL Java 8.0, so when I tried to run the ApplicationBootConfiguration class the example provided, I got failed with the following stack:

`Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-04-17 16:09:33.549 ERROR 19184 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.ericsson.dnew.bid.eris4j.Eris4jApplication.main(Eris4jApplication.java:15) [classes/:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:126) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:86) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:409) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:174) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 8 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLServletRegistrationBean' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLServletRegistrationBean' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLServlet' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.servlet.GraphQLServlet]: Factory method 'graphQLServlet' threw exception; nested exception is java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:729) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:470) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:225) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:213) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:90) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:79) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:250) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:237) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:54) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5204) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLServlet' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.servlet.GraphQLServlet]: Factory method 'graphQLServlet' threw exception; nested exception is java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 24 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.servlet.GraphQLServlet]: Factory method 'graphQLServlet' threw exception; nested exception is java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 37 common frames omitted
Caused by: java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at graphql.servlet.SimpleGraphQLServlet.<init>(SimpleGraphQLServlet.java:44) ~[graphql-java-servlet-4.6.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration.graphQLServlet(GraphQLWebAutoConfiguration.java:155) ~[graphql-spring-boot-autoconfigure-4.0.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration$$EnhancerBySpringCGLIB$$cf37fa8b.CGLIB$graphQLServlet$1(<generated>) ~[graphql-spring-boot-autoconfigure-4.0.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration$$EnhancerBySpringCGLIB$$cf37fa8b$$FastClassBySpringCGLIB$$42e646ff.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-4.0.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration$$EnhancerBySpringCGLIB$$cf37fa8b.graphQLServlet(<generated>) ~[graphql-spring-boot-autoconfigure-4.0.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: graphql.execution.instrumentation.NoOpInstrumentation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 50 common frames omitted
`

So, the example needs to be upgraded to adapt to new GraphQL Java 8.

**Comment by AllanWang** [comment]
Is it just me or did the latest version update break graphiql?

```
[WARN ] 2018-05-22 23:32:00.586 [http-nio-9000-exec-10] PageNotFound - No mapping found for HTTP request with URI [/vendor/react.min.js] in DispatcherServlet with name 'dispatcherServlet'
[WARN ] 2018-05-22 23:32:00.605 [http-nio-9000-exec-9] PageNotFound - No mapping found for HTTP request with URI [/vendor/react-dom.min.js] in DispatcherServlet with name 'dispatcherServlet'
[WARN ] 2018-05-22 23:32:00.628 [http-nio-9000-exec-3] PageNotFound - No mapping found for HTTP request with URI [/vendor/graphiql.min.js] in DispatcherServlet with name 'dispatcherServlet'
[WARN ] 2018-05-22 23:32:00.630 [http-nio-9000-exec-1] PageNotFound - No mapping found for HTTP request with URI [/vendor/graphiql.min.css] in DispatcherServlet with name 'dispatcherServlet'
```

I don't see how any of my changes could stop it from loading.

Intellij is also warning that `pageTitle: GraphiQL` could not be resolved

**Comment by AllanWang** [comment]
@apottere I have only added beans for the graphql schema and the context builder. I will try reverting versions again and seeing if that is the sole cause of the issue

**Comment by apottere** [comment]
It should be, part of that version was serving files from the classpath instead of a CDN.  I'd be interested if you could send me a stripped-down project that reproduces the issue you're having.

**Comment by AllanWang** [comment]
The full project is [here](https://github.com/AllanWang/McGill-Data/tree/feature/graphql-db)

with the main class under the server module. I just tested with graphql_spring = 4.1.0 and graphql_java = 6.0 and it still didn't work, so I'm trying to figure out if there was some other dependency that's wrong or if I somehow messed everything up

**Comment by AllanWang** [comment]
Reverting to 4.0.0, which was what I was previously on, worked. Anything beyond 4.1.0 and the css paths return 404. I also removed all of my own filters, so I don't think there's anything I did to prevent the requests. It's weird that you were able to load with a test project though, so I'm wondering what I've done

**Comment by n0mer** [comment]
@AllanWang is this working in 5.0.2 ?

**Comment by yami12376** [comment]
I've got these errors on 5.0.2:

`2019-01-21 11:31:46.067  WARN [dictionary,7d8439fa155f6e60,7d8439fa155f6e60,false] 1780 --- [nio-8999-exec-9] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/react.min.js] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.068  WARN [dictionary,c4a756044e223cd4,c4a756044e223cd4,false] 1780 --- [io-8999-exec-10] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/react-dom.min.js] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.071  WARN [dictionary,5ff78f07df4ec7e1,5ff78f07df4ec7e1,false] 1780 --- [nio-8999-exec-8] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/graphiql.min.css] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.071  WARN [dictionary,ad8fd777da6a0eca,ad8fd777da6a0eca,false] 1780 --- [nio-8999-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/graphiql.min.js] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.150  WARN [dictionary,c69d44066aac02af,c69d44066aac02af,false] 1780 --- [nio-8999-exec-5] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/react.min.js] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.166  WARN [dictionary,f7eddb83899836b7,f7eddb83899836b7,false] 1780 --- [nio-8999-exec-3] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/react-dom.min.js] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.173  WARN [dictionary,3818a296d664f820,3818a296d664f820,false] 1780 --- [nio-8999-exec-7] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/graphiql.min.js] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:46.173  WARN [dictionary,79a01ac91ca33832,79a01ac91ca33832,false] 1780 --- [nio-8999-exec-4] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/vendor/graphiql.min.css] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:52.027  WARN [dictionary,ae3d69b8620faa5c,ae3d69b8620faa5c,false] 1780 --- [nio-8999-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:31:57.464  WARN [dictionary,c70792bc85b1e484,c70792bc85b1e484,false] 1780 --- [nio-8999-exec-5] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:32:01.737  WARN [dictionary,57ddc8d708acfe8b,57ddc8d708acfe8b,false] 1780 --- [nio-8999-exec-9] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:32:17.242  WARN [dictionary,2d33b73ea0e6c224,2d33b73ea0e6c224,false] 1780 --- [nio-8999-exec-7] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:32:28.012  WARN [dictionary,c677e1deeea06413,c677e1deeea06413,false] 1780 --- [nio-8999-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:32:44.836  WARN [dictionary,423fdea75b196f40,423fdea75b196f40,false] 1780 --- [nio-8999-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
2019-01-21 11:33:02.452  WARN [dictionary,854fbd419c9c3a93,854fbd419c9c3a93,true] 1780 --- [nio-8999-exec-4] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/subscriptions] in DispatcherServlet with name 'dispatcherServlet'
`
