### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface graphql.schema.DataFetchingEnvironment, but class was expected

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [graphql-java/graphql-spring-boot#7]
I'm running graphql-spring-boot at it's latest `3.2.0` and I seem to get the stacktrace regarding the `DataFetchingEnvironment` (provided at the end)? 

My graphql query looks like this:

```
{
  organisation {
    name,
    id
  }
}
```

The GraphQLSchemaQuery of my API looks like this:

```java
@GraphQLObject("GraphQLApi")
public class QueryApi {
    @GraphQLNonNull
    @GraphQLField("version")
    @GraphQLDescription("The version number of this API")
    public static final String VERSION = "0.1-springboot-alpha";

    @Autowired
    @GraphQLIgnore
    private OrganisationService organisationService;

    @GraphQLField("organisations")
    public List<Organisation> getOrganisations() {
        return organisationService.getOrganisations();
    }

    @GraphQLField("organisation")
    public Organisation getOrganisation(@GraphQLIn("id") Integer id) {
        return organisationService.getOrganisation(id);
    }
}
```

**When I query for `{ version }` then data is returned. But when I query either organisation fields, then I get the error on the server side.**

```
java.lang.IncompatibleClassChangeError: Found interface graphql.schema.DataFetchingEnvironment, but class was expected
	at com.oembedler.moon.graphql.engine.ReflectionGraphQLDataFetcher.collectBindByClassValues(ReflectionGraphQLDataFetcher.java:89) ~[spring-graphql-common-2.1.0-2016-05-22T16-50-32.jar:na]
	at com.oembedler.moon.graphql.engine.ReflectionGraphQLDataFetcher.get(ReflectionGraphQLDataFetcher.java:69) ~[spring-graphql-common-2.1.0-2016-05-22T16-50-32.jar:na]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:66) ~[graphql-java-2.4.0.jar:na]
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18) ~[graphql-java-2.4.0.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:85) ~[graphql-java-2.4.0.jar:na]
	at graphql.execution.Execution.execute(Execution.java:44) ~[graphql-java-2.4.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:201) ~[graphql-java-2.4.0.jar:na]
	at graphql.servlet.GraphQLServlet.query(GraphQLServlet.java:274) [graphql-java-servlet-3.0.1.jar:na]
	at graphql.servlet.GraphQLServlet.lambda$new$1(GraphQLServlet.java:187) [graphql-java-servlet-3.0.1.jar:na]
	at graphql.servlet.GraphQLServlet.doRequest(GraphQLServlet.java:230) [graphql-java-servlet-3.0.1.jar:na]
	at graphql.servlet.GraphQLServlet.doPost(GraphQLServlet.java:248) [graphql-java-servlet-3.0.1.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RC1.jar:5.0.0.RC1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Adding the `Service` class just in case.**

```java
@Service
public class OrganisationServiceImpl implements OrganisationService {
    private List<Organisation> organisations = new ArrayList<>(Arrays.asList(
            new Organisation("Home", "HOME"),
            new Organisation("Shiraaz", "SHIR"),
    ));

    public Organisation getOrganisation(Integer id) {
        return organisations.get(id);
    }

    public List<Organisation> getOrganisations() {
        return organisations;
    }

    @Override
    public Organisation addOrganisation(String name, String id) {
        final Organisation result = new Organisation(name, id);
        organisations.add(result);

        return result;
    }
}
```

**Comment by apottere** [comment]
This is actually because of a breaking change from graphql-java `2.3.0` to `2.4.0`, `DataFetchingEnvironment` was updated to be an interface instead of a class.  graphql-spring-boot pulls in `2.4.0`, but it looks like the annotations library doesn't work with that yet.
