### ISSUE TITLE
Can't deploy to Cloud Foundry. HELP!!!

### ISSUE THREAD

**Issue by kourtneya** [graphql-java/graphql-spring-boot#86]
When I run my code base locally it runs perfectly fine. However, when deploying the artifact to cloud foundry I get the following stacktrace. 

   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLSchema' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1177)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	... 24 common frames omitted
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at graphql.schema.GraphQLObjectType$Builder.field(GraphQLObjectType.java:173)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	... 25 common frames omitted
   2018-06-26T13:14:45.40-0500 [APP/PROC/WEB/0] OUT Jun 26, 2018 18:14:45 +0000 [8 5] com.newrelic.agent.Agent INFO: JVM is shutting down
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT Caused by: java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.<init>(MethodFieldResolver.kt:131)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at graphql.schema.GraphQLObjectType$Builder.field(GraphQLObjectType.java:173)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2d7ff9a2.graphQLSchema(<generated>)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	... 25 common frames omitted
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1177)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1071)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.barnes.og.cases.CasesServiceApp.main(CasesServiceApp.java:82)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.esotericsoftware.reflectasm.MethodAccess.get(MethodAccess.java:126)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.MethodFieldResolver.createDataFetcher(MethodFieldResolver.kt:98)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:126)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.SchemaParser.createObject(SchemaParser.kt:124)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.graphQLSchema(GraphQLJavaToolsAutoConfiguration.java:87)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2d7ff9a2$$FastClassBySpringCGLIB$$af4f8c1d.invoke(<generated>)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2d7ff9a2.graphQLSchema(<generated>)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
   2018-06-26T13:14:45.40-0500 [APP/PROC/WEB/0] OUT Jun 26, 2018 18:14:45 +0000 [8 5] com.newrelic.agent.Agent INFO: New Relic Agent has shutdown
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:126)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2d7ff9a2.CGLIB$graphQLSchema$0(<generated>)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 2018-06-26 18:14:45.398 ERROR 8 --- [           main] com.barnes.og.cases.CasesServiceApp        : ERROR: An error occured while starting the microservice.
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT Caused by: java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.<init>(MethodFieldResolver.kt:131)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:46)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.SchemaParser.parseSchemaObjects(SchemaParser.kt:85)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.coxautodev.graphql.tools.SchemaParser.makeExecutableSchema(SchemaParser.kt:109)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2d7ff9a2.CGLIB$graphQLSchema$0(<generated>)
   2018-06-26T13:14:45.39-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
   2018-06-26T13:14:45.75-0500 [APP/PROC/WEB/0] OUT Exit status 0
   2018-06-26T13:14:45.79-0500 [CELL/0] OUT Destroying container
   2018-06-26T13:14:45.82-0500 [API/4] OUT Process has crashed with type: "web"

**Comment by kourtneyb12** [comment]
Using Spring 1.5.14

**Comment by oliemansm** [comment]
Sounds like an issue with Cloud Foundry and not specifically to this GraphQL project. No experience with Cloud Foundry myself really. Maybe a different JRE is used there? E.g. OpenJDK instead of Oracle. Something like that?

**Comment by oliemansm** [comment]
Since I don't see any responses from you anymore, I'm going to assume you either fixed it or raised an issue on StackOverflow for this.
